# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EC4kecKh_NR_MTt5tZS0vLaloWvlMLIw
"""

movies=("Interstellar","Avatar","Frozen","Conjuring","Harry Potter")
for movie in movies:
  print(movie)