# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYWYQX-idKJ9bKhlXrIvq2PKsjcQhBfn
"""

name= "Prachi"
age= "17"
height= "5.2"
is_student= True