# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofbimcrEU5jaxVbu_xbJHnkRH1lIvKX2
"""

numbers=[1,2,3,4,5]
fruits=["apple","banana","mango"]
print(fruits[0])
fruits.append("orange")
print(fruits)
for fruit in fruits:
  print(fruit)