# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NShT2Ju1Bx1zPMiCGPlIzj7LBSdk9Tp
"""

str1 = "Hie"
str2 = "Prachi"
result = (str1+str2)*3
print(result)