# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aK7Fbl5rDqltroxN_fmOAxrxBM11Owxe
"""

num= 1,2,3,4,5,6,7,8,9,10
for no in num:
  if no % 2 == 0:
    print (no)