# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cs9jTcwuQ-zqIS9WQXb0PVaAQRalPp7G
"""

print("Hello, Data Science !")

