# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWYb5TKyhAelaMIiaIFUFwWFd-AHzyJb
"""

age=13
if age<12:
  print("Child")
elif age<=19:
  print("Teen")
else:
  print("Adult")