# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KTQcQBRj4yIUhhUBX9s6auCYNoRFWNB
"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Hie", name,"you are",age,"years old")