# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcoeVk82ZTzPsogPfiIEg-NnvtnRmqt3
"""

greeting="Hi"
name="Prachi"
print(greeting+name)
print(name*3)